version: '3'
services:
  config-server:
    container_name: config-server
    image: config-server:v1
    restart: always
    ports:
      - "8888:8888"
    networks:
      - booking-cloud
    expose:
      - 8888
    depends_on:
      - eureka-server
  eureka-server:
    container_name: eureka-server
    restart: always
    image: eureka-server:v1
    ports:
      - "8761:8761"
    networks:
      - booking-cloud
    expose:
      - 8761
  api-gateway:
    container_name: api-gateway
    restart: always
    image: api-gateway:v1
    ports:
      - "8080:8080"
    networks:
      - booking-cloud
    depends_on:
      - config-server
      - eureka-server
  db-availabilities:
    container_name: db-availabilities
    image: postgres:latest
    restart: always
    networks:
      - postgres
      - booking-cloud
    environment:
      POSTGRES_DB: ms_availabilities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    depends_on:
      - config-server
      - eureka-server
  availability-service:
    container_name: availability-service
    image: availability:v1
    restart: always
    networks:
      - postgres
      - booking-cloud
    depends_on:
      - config-server
      - eureka-server
      - db-availabilities
  db-bookings:
    container_name: db-bookings
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    networks:
      - mysql
      - booking-cloud
    environment:
      MYSQL_DATABASE: ms_bookings
      MYSQL_USER: Juanem
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - config-server
      - eureka-server
  booking-service:
    container_name: booking-service
    image: booking:v1
    restart: always
    networks:
      - mysql
      - booking-cloud
    depends_on:
      - config-server
      - eureka-server
      - db-bookings
  db-bu:
    container_name: db-bu
    image: postgres:latest
    restart: always
    networks:
      - postgres
      - booking-cloud
    environment:
      POSTGRES_DB: ms_business
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    depends_on:
      - config-server
      - eureka-server
  business-service:
    container_name: business-service
    image: business:v1
    restart: always
    networks:
      - postgres
      - booking-cloud
    depends_on:
      - config-server
      - eureka-server
      - db-bu
  db-payments:
    container_name: db-payments
    image: mysql:latest
    restart: always
    networks:
      - mysql
      - booking-cloud
    environment:
      MYSQL_DATABASE: ms_payments
      MYSQL_USER: Juanem
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - config-server
      - eureka-server
  payment-service:
    container_name: payment-service
    image: payment:v1
    restart: always
    networks:
      - mysql
      - booking-cloud
    depends_on:
      - config-server
      - eureka-server
      - db-payments
  db-rates:
    container_name: db-rates
    image: postgres:latest
    restart: always
    networks:
      - postgres
      - booking-cloud
    environment:
      POSTGRES_DB: ms_rates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    depends_on:
      - config-server
      - eureka-server
  rate-service:
    container_name: rate-service
    image: rate:v1
    restart: always
    networks:
      - postgres
      - booking-cloud
    depends_on:
      - config-server
      - eureka-server
      - db-rates
networks:
  postgres:
    driver: bridge
  mysql:
    driver: bridge
  booking-cloud:
    driver: bridge